### ISSUE TITLE
感觉还不错，公司最近要做这样的效果，不知道能帮忙写个demo或者给个思路吗

### ISSUE THREAD

**Issue by songxing10000** [lqcjdx/DemoInPutPasswordView#2]
![snip20150819_1](https://cloud.githubusercontent.com/assets/10040131/9347987/5f188ea0-4663-11e5-9bef-16fffee3625c.png)

**Comment by ApesTalk** [comment]
@songxing10000 这个你要先看下支付宝官方对应的接口是怎么设计的，看需要那几个字段啊，输入密码之后你调用一下支付宝的接口就差不多了吧。

**Comment by songxing10000** [comment]
我的意思是界面能在你这个框架基础上修改成需要的吗

**Comment by ApesTalk** [comment]
@songxing10000 哦，可以的啊，你看下我的源码，可以根据你的需要自行调整和修改。
